title: "Emil Mallmin"
description: "Person webpage"
remote_theme: mmistakes/minimal-mistakes

# Optional: Markdown and posts
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
