title: "My Whisky Blog"
description: "Tasting notes and grades for whiskies I explore"
remote_theme: mmistakes/minimal-mistakes

# Optional: Markdown and posts
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Optional: baseurl if deploying to github.io/USERNAME
# baseurl: ""
