remote_theme: mmistakes/minimal-mistakes
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

include: ["_pages"]


title: "Emil Mallmin"
email: emallmin@evolbio.mpg.de
description: "Academic CV and personal website"
baseurl: "" # leave empty for user site
url: "emilmallmin.com"

author:
  name: "Emil Mallmin"
  avatar: "/assets/images/avatar_square.jpg"
  bio: "Statistical physicist, specialising on understanding ecological communities | PhD"
  location: "Max Planck Institute for Evolutionary Biology, Pl√∂n, Germany"
  links:
    - label: "email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:emallmin@evolbio.mpg.de"


# defaults:
#   # _posts
#   - scope:
#       path: ""
#       type: posts
#     values:
#       layout: single
#       author_profile: true
#       read_time: false
#       comments: true
#       share: true
#       related: true
