remote_theme: mmistakes/minimal-mistakes
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

include: ["_pages"]


title: "Emil Mallmin"
email: emallmin@evolbio.mpg.de
description: "Academic CV and personal website"
baseurl: "" # leave empty for user site
url: "emilmallmin.com"

author:
  name: "Emil Mallmin"
  avatar: "/assets/images/avatar_square.jpg"
  bio: "Statistical physicist, specialising on understanding ecological communities | PhD"

# Social links (optional)
# social:
#   github: "ericjohnsson"
#   linkedin: "eric-johnsson"
#   twitter: "ericjohnsson"

